### ISSUE TITLE
Error: FileNotFoundError on fluter project with module

### ISSUE THREAD

**Issue by romulogomesbsi** [java-james/flutter_dotenv#89]
I'm working on a flutter project with Module. This package doesn't work correctly here, but if I build a normal project, I don't get this error.

`E/flutter (27891): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'FileNotFoundError'
E/flutter (27891): #0      DotEnv._getEntriesFromFile
dotenv.dart:111
E/flutter (27891): <asynchronous suspension>
E/flutter (27891): #1      DotEnv.load
dotenv.dart:68
E/flutter (27891): <asynchronous suspension>
E/flutter (27891): #2      main
main.dart:9
E/flutter (27891): <asynchronous suspension>
E/flutter (27891):`

**Comment by Dev-Ayan-Dasgupta** [comment]
Did you include .env in pubspec.yaml under assets?

**Comment by neeraj15022001** [comment]
<img width="1047" alt="Screenshot 2023-08-10 at 1 15 29 AM" src="https://github.com/java-james/flutter_dotenv/assets/55191873/6c7b0c17-90b0-407c-b774-a4cc3e2f5c5b">

Facing same issue when running Flutter on web, though i haven't tried on other platforms. 

Pubspec.yaml
<img width="805" alt="Screenshot 2023-08-10 at 1 17 11 AM" src="https://github.com/java-james/flutter_dotenv/assets/55191873/a4bcee0c-6c3d-4e2c-a614-d739e5938884">
I have added env to assets as told in docs

**Comment by jsmile** [comment]
I have the same trouble:

`E/flutter (28853): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] **Unhandled Exception: Instance of 'FileNotFoundError'`**

**- my pubspec.yaml** 
```
name: open_weather_cubit
description: A Flutter BLoC - OpenWeather Cubit project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/loading.gif
  - .env
```

- I made '.env' file in the project root.
- I have loaded in a flutter app
```
void main() async {
  await dotenv.load(fileName: '.env');
  runApp(const MyApp());
}  

```
